# Generated by Django 3.1.7 on 2021-09-26 13:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('some', '0010_auto_20210329_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarytoken',
            name='last_action',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 26, 13, 21, 1, 367715, tzinfo=utc)),
        ),
    ]
