# Generated by Django 3.1.7 on 2021-10-06 09:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('some', '0011_auto_20210926_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarytoken',
            name='last_action',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 9, 27, 22, 991835, tzinfo=utc)),
        ),
    ]
