# Generated by Django 3.1.7 on 2021-10-06 09:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('some', '0013_auto_20211006_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarytoken',
            name='last_action',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 9, 54, 58, 399950, tzinfo=utc)),
        ),
    ]
